application:
  name: abraham-yusuf-backend
  project: abraham-yusuf
  publicly_accessible: true
  port: 8080
  storage: # qovery will attach automatically a SSD storage on /srv/app
    - name: data
      type: ssd
      cpu: 250m
      ram: 256MB
      #size: 1GB
      mount_point: /srv/app
databases:
- type: postgresql # qovery will create a managed PostgreSQL database
  version: 12
  name: psql
routers:
- name: main
  custom_domains: # optional: only if you want to use your domain
  - branch: master
    domain: https://main-ire5loxgd5oc824n-svc.qovery.io
  routes:
  - application_name: abraham-yusuf
    paths:
    - /*
